### ISSUE TITLE
Self-update fails on Arch Linux

### ISSUE THREAD

**Issue by mccurdyc** [fastly/cli#123]
**Version**
Applies to all versions

Please paste the output of `fastly version` here.

```
Fastly CLI version 0.10.0 (306abd1)
Built with go version go1.14.3 linux/amd64
```

**System Info**

```
$ uname -a
Linux hostname 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
```

**What happened**
1. `wget https://github.com/fastly/cli/releases/download/v0.10.0/fastly_v0.10.0_linux-amd64.tar.gz`
2. `tar -xzf fastly_v0.10.0_linux-amd64.tar.gz -C /usr/local/bin`
3. Update using `fastly update`
```
$ sudo /usr/local/bin/fastly update
- Initializing...Current version: 0.10.0
Latest version: 0.12.0
✓ Initializing...
✓ Fetching latest release...
✗ Replacing binary...

ERROR: error moving latest binary in place: error creating destination file: open /usr/local/bin/fastly: text file busy.

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

**Comment by mccurdyc** [comment]
What I do instead is use the steps above and just replace the binary rather than using `fastly update`.

We can  close this, but did want to document for anyone who may run into this in the future.

**Comment by Integralist** [comment]
@mccurdyc @swagitda 👋🏻 this issue was opened before I started at Fastly so I've only just seen it 😬 

We had a similar issue with a Windows user, and this was the implementation we ended up with:

https://github.com/fastly/cli/blob/5917e4d81f1180428f00286e26d6ac0a2b4e8001/pkg/commands/update/root.go#L99-L123

I'm going to try and get this scheduled into our upcoming Q3 work.
