### ISSUE TITLE
`go install` no longer works on a fresh clone

### ISSUE THREAD

**Issue by peterbourgon** [fastly/cli#332]
Generated — or, in this case, fetched — code/files should be checked in, so that `go install`, `go test`, etc. works on a fresh clone without other steps. At the moment, `make config` is a prerequisite to a successful build. Oops. The `cmd/fastly/static/fastly.toml` file should be checked in. Does anything else need to happen, e.g. a CI step to make sure it's current?

**Comment by Integralist** [comment]
The CI release flow pulls the latest config version into `cmd/fastly/static/fastly.toml` before cutting a release (https://github.com/fastly/cli/blob/main/.github/workflows/tag_release.yml#L21-L23) and so it wasn't felt it was necessary to have it checked in (I also feel like there was an issue with having it checked in, although I can't recall the particular details now or why it would have been an issue 🤔).

As far as the Makefile is concerned we have the `all`, `build` and `test` targets setup so that the `config` target is a prerequisite and the understanding was that people would use `make test` to run the tests and that would ensure the config was pulled, or if they just wanted to go ahead and build then `make build` would again ensure the code would compile, but I appreciate that some people pulling the repo might not be aware of the Makefile and subsequently might attempt to run `go test`.

**Comment by peterbourgon** [comment]
> As far as the Makefile is concerned we have the all, build and test targets setup so that the config target is a prerequisite and the understanding was that people would use make test to run the tests

Not me! 🙃 Go is an esoteric language with lots of opinions, and I dunno maybe this is one of the softer ones, but it's good practice to make sure this always succeeds:

```
git clone git@github.com:your/go-project
cd go-project
go build ./...
go test ./...
```

This means checking in stuff like generated .protos, the output of `go generate`, and, yeah, any preconditions established by make targets you expect will "always" be run. Makefiles are great! But for Go stuff, especially pure-Go stuff like this repo, they should be opt-in.

Or, look at it this way — the file is a requirement for compilation, so the project isn't buildable until it's there. Does the actual content matter? Like, does some code or test expect a certain structure, or key, or value? If so, you definitely want to track that in version control! And if not, you can just keep a dummy or default copy checked in, and overwrite it for releases, it's doing no harm.

**Comment by Integralist** [comment]
OK, gotcha. Thanks for the education around this stuff, I'll look at resolving this shortly 👍🏻
