### ISSUE TITLE
 Add "sync" function for edge dictionary items

### ISSUE THREAD

**Issue by benzvan** [fastly/cli#379]
As a fastly configuration maintainer

When I change my local version of an edge dictionary

I want to easily synchronize adds, updates, and deletes with fastly

So that I don't leave cruft behind by forgetting to delete values

Notes:
This is a larger enhancement but I'm hoping it's valuable to other users. We have a git repo where we maintain batch files for a few edge dictionaries and use the fastly CLI to push those batches up to our service. It would be great if my local copy of the dictionary, stored in json, could be synchronized with the remote copy via the CLI instead of manually maintaining batch files that have an expectation of the remote values.

**Comment by JakeChampion** [comment]
@benzvan in your current workflow, is this the command you are using?
`fastly dictionaryitem  batchmodify  --dictionary-id $dictionary_id --file dictionary_items.json`

**Comment by benzvan** [comment]
Yep. That's the one. We're using `op: upsert` for basically all the items.

**Comment by benzvan** [comment]
I'm coming back to this today because we have an effort on our team to simplify the way we maintain our edge dictionary. I'd love to see something like 

```
fastly dictionary set --dictionary-id $dictionary_id --file dictionary_items.json
```
Where `dictionary_items.json` ==
```
{
  "dictionary_key1": "value1",
  "dictionary_key2": "value2",
  "dictionary_key3": "value3",
  "dictionary_key4": "value4"
}
```
and the result is the `$dictionary_id` matches the key/value pairs in the file when completed. If this was a built-in fastly API function, it would also simplify some of the terraform we use to copy k/v pairs into a dictionary.

**Comment by Integralist** [comment]
👋🏻 

It looks like this feature request is starting to tread on the toes of the [Fastly Terraform provider](https://registry.terraform.io/providers/fastly/fastly/latest/docs), a tool designed for this sort of task (if I'm understanding the requirements correctly).

With that in mind, I'm not sure if it makes sense to duplicate that effort in the CLI. Open to further discussion on this.

**Comment by benzvan** [comment]
We ended up writing a shell script utility that did it for us. The problem with using the terraform provider is this team wants to separate the edge dictionary deployments (for feature toggles etc.) from the service deployment which is already handled by terraform. I'm not sure it would be possible to have one terraform configuration responsible for the edge dictionaries and one terraform configuration responsible for everything else in the service including opaque dictionaries containing secrets.

**Comment by Integralist** [comment]
> The problem with using the terraform provider is this team wants to separate the edge dictionary deployments (for feature toggles etc.) from the service deployment which is already handled by terraform.

I guess it's hard for me to comment here as I don't know the full setup of your Terraform project, but I presume it's not possible for you to make PR changes to your Terraform configuration that affect just the `fastly_service_dictionary_items` resource? You'd also need to set `manage_items=true` to ensure that only Terraform can control the contents of the dictionary items.

> I'm not sure it would be possible to have one terraform configuration responsible for the edge dictionaries and one terraform configuration responsible for everything else in the service including opaque dictionaries containing secrets.

I think this would be possible. 

One Terraform project would manage the `fastly_service_vcl` resource and the [`dictionary`](https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_vcl#nested-schema-for-dictionary) block within that resource (which is just responsible for managing the dictionary 'container', and not the items within the dictionary). 

The second Terraform project would configure just the `fastly_service_dictionary_items`. You'd then either need to manually inject the Service ID and Dictionary ID into this resource _or_ you could import the `fastly_service_vcl` so it (and the Dictionary ID) exists in this project's state file. That way you could dynamically pull the Server and Dictionary IDs into the `fastly_service_dictionary_items` resource (but importing feels unnecessary and just manually grabbing those IDs would be much simpler). Then you set `manage_items=true` on the `fastly_service_dictionary_items` resource so that Terraform would be in complete control of the edge dictionary contents, but any changes outside of Terraform (e.g. API calls that insert new keys into the dictionary would be lost).

I guess it just depends on what you mean by 'sync' in this context.

**Comment by benzvan** [comment]
I'm pretty sure the terraform configuration acts on the `service` level, so two terraform projects can't manage two different things within one fastly service.

That said, probably the best way to do this would be to put all the configuration into a single terraform project and only change the things you want to change. 12 Factor would have a disagreement since that means keeping the configuration (edge dicts) and code (vcl) in the same place so the feature probably still has value to teams that haven't written their own way of doing it.

**Comment by Integralist** [comment]
👋🏻 

> I'm pretty sure the terraform configuration acts on the service level, so two terraform projects can't manage two different things within one fastly service.

So I have a working example of this.

I have two separate folders `terraform-dict-management-project-a` and `terraform-dict-management-project-b`.

In the first, I have the following configuration which creates a service with a dictionary:

```hcl
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
      version = "5.2.2"
    }
  }
}

resource "fastly_service_vcl" "myservice" {
  name = "tf-service-managing-dictionary-container"

  domain {
    name = "demo.integralist-testing.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  dictionary {
    name = "dict_testing"
  }

  force_destroy = true
}
```

In the latter directory I have the following configuration, which populates the dictionary with data...

```hcl
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
      version = "5.2.2"
    }
  }
}

resource "fastly_service_dictionary_items" "items" {
  service_id = "<value pulled from other tf project state file>"
  dictionary_id = "<value pulled from other tf project state file>"

  items = {
    key1: "value1"
    key2: "value2"
  }

  manage_items = true
}
```

These are two separate Terraform projects. I'm able to now use the latter project to separately manage the dictionary items.

**Comment by benzvan** [comment]
Ok, that's cool, and it completely solves this problem. It also allows pulling secrets from vault to insert into a dictionary.
