### ISSUE TITLE
deb and rpm packages install the binary in `/usr/local` instead of `/usr/local/bin`

### ISSUE THREAD

**Issue by avidal** [fastly/cli#53]
https://github.com/fastly/cli/blob/34ea5415bd09100788b69040f7c9cec1d927f25e/.goreleaser.yml#L67

Not sure if this was intentional or not, but my experience has been that distributions don't place `/usr/local/` on the `$PATH`. Should this be `/usr/local/bin`?

**Comment by phamann** [comment]
Hey @avidal thank you for the report. You are indeed correct and this is a regression that we should fix. We previously used to package have a `bin` directory inside the release packages which solved this, and subsequently had to remove due to assumptions the `fastly update` logic makes.  I will submit a patch which will go out in the next release.
