### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by pnorman** [fastly/cli#605]
**Version**
Built with 4fdd620

**What happened**

When running `make` I get the following error

```
   • building...
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=4fdd620de7f8ae6a749bff970902702bb7c65a0a latest tag=v3.1.1
   ⨯ build failed after 0.21s error=git tag v3.1.1 was not made against commit 4fdd620de7f8ae6a749bff970902702bb7c65a0a
make: *** [Makefile:30: fastly] Error 1
```

**Comment by pnorman** [comment]
If I check out the `v3.1.1` tag, it builds past this point, but nothing in the [instructions mentions needing to check out a tag](https://github.com/fastly/cli/blob/main/DEVELOP.md)

**Comment by Integralist** [comment]
Hi @pnorman 

I didn't get a notification for this ticket I'm afraid so thanks for your patience.

I typically run `make install` when I'm developing locally (and ensure that the go install directory is in my PATH).

I only ever use a target like `make fastly` (which is the default target if no target is explicitly specified) if I'm looking to validate [goreleaser](https://goreleaser.com)'s behaviours.

As far as the error is concerned goreleaser will check the latest git tag against the latest commit and will complain if they don't match (which can happen if you're developing and committing locally). You can pass flags to goreleaser to get it to ignore these validation checks.

**Comment by Integralist** [comment]
Also, just to clarify, that the error is happening in the main line branch because we've since added new commits to `main` and not yet cut a new release and subsequently created a new tag.

Because this is something that can happen regularly while we're developing features to be released to customers I think the best thing for us to do is to update the Makefile to ensure the default target simply executes a compilation of the project.
