### ISSUE TITLE
[FEATURE REQUEST] Please add CONDITIONS to the CLI

### ISSUE THREAD

**Issue by leoncowle** [fastly/cli#841]
**Is your feature request related to a problem? Please describe.**
Missing the ability to use the CLI to create/manage CONDITIONS.

**Describe the solution you'd like**
Implement a command in the CLI to manage CONDITIONS.

**Describe alternatives you've considered**
Closed issue #497 mentions using it in VCL, but I'm unclear how -- when it's a Request condition that you want to attach to a backend. Alternatively, we can call the API directly. However, this is not the proper solution (if you want to use the CLI at all). Right now, my approach is to have a script which does:
```
curl -X POST "https://api.fastly.com/service/<svcid>/version/<ver>/condition" ... ... ...
fastly backend create --request-condition <condition created using cURL above> ... ... ...
```
Would be much better if we were able to use the CLI for all steps.

**Comment by Integralist** [comment]
Hi @leoncowle 

Nearly all of the UI features (for a 'Deliver' service) are shortcuts to help avoid writing your own VCL code. 
A 'Deliver' service uses Varnish/VCL and so that's why all these UI features essentially generate VCL code.

So when you run something like...

```shell
# Create a 'condition' object
$ curl -i  -X POST "https://api.fastly.com/service/<SERVICE_ID>/version/<VERSION>/condition" -H "Fastly-Key: $FASTLY_API_TOKEN" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" -d "name=test-request-condition&statement=req.url.basename+%3D%3D+%22index.html%22&type=REQUEST&priority=10"

# Create a 'backend' object (and attach the condition object to it)
$ fastly backend create --request-condition test-request-condition --name foo --address <ADDRESS> --service-id <SERVICE_ID> --version <VERSION>
```

What is happening is, a 'condition' object is created and within your service a corresponding chunk of VCL code is generated and added inside of a _default_ `vcl_recv` subroutine that Fastly generates for your service. 

That chunk of VCL code looks something like the following, which is the VCL generated from the above example curl/cli command shown above...

```vcl
if (req.url.basename == "index.html") {
  set req.backend = F_foo;
}
```

You can see all the VCL code is really doing is saying "once the condition is met, make sure the 'backend' object 'foo' is used.

> **NOTE:** You can check this yourself by going into the Fastly management UI and clicking on the "{} Show VCL" link (so for example you'll also see the `fastly backend create` command will have produced a 'backend' VCL object).

You can recreate that same behaviour using the existing set of CLI commands. 

The first thing to do is to create a backend, in my example I named it 'foo'...

```shell
$ fastly backend create --name foo --address <ADDRESS> --service-id <SERVICE_ID> --version <VERSION>
```

Next, create a local `main.vcl` file and enter the following VCL, so for my example that looks like the following...

```vcl
sub vcl_recv {
  #FASTLY recv

  if (req.url.basename == "index.html") { // change this to whatever your 'condition' needs to be
    set req.backend = F_foo;
  }

  // I've included this condition as it was part of the 'default' VCL Fastly generates for you if you don't upload your own custom VCL.
  // Feel free to remove it if you think you don't require it.
  if (req.request != "HEAD" && req.request != "GET" && req.request != "FASTLYPURGE") {
    return(pass);
  }
  
  return(lookup);
}
```

> **NOTE:** The VCL format for a backend name is actually `F_<YOUR_BACKEND_NAME>`.

Next, you'll need to upload this VCL code to your service using the following CLI command...

```shell
$ fastly vcl custom create --name main --content main.vcl --main --service-id <SERVICE_ID> --version <VERSION>
```

Now, _all that said_, I can see how this isn't ideal for customers who are unfamiliar with VCL and so I'm going to create a ticket internally to track implementing conditions and possibly some of the other 'VCL objects' available ([docs](https://developer.fastly.com/reference/api/vcl-services/)).

**Comment by Integralist** [comment]
Thanks @leoncowle for the extra context, much appreciated 👍🏻 

I came to Fastly from a large organisation that too had a LOT of custom VCL and no automation, so I feel your pain 🙂 

As I mentioned above, now I've had some first-hand experience with the actual 'flow' that someone would have to go through to set this up (which is made a lot harder for customers who _don't_ know VCL as well as we do) I can totally see how having the 'conditions' exposed as a command in the CLI. 

So we do now have an internal ticket tracking this request. I can't give an ETA on when it will be done, but rest assured we're now aware that this is a pain point and will look to address it.
