### ISSUE TITLE
[FEATURE REQUEST] Allow disabling viceroy auto update

### ISSUE THREAD

**Issue by shyim** [fastly/cli#858]
**Is your feature request related to a problem? Please describe.**
We want to package fastly cli in proper way in nixpkgs so we need to package also viceroy. So Fastly does not download it anymore

**Describe the solution you'd like**
A environment variable to disable looking for updates and just taking the in the PATH given viceroy

**Describe alternatives you've considered**
Patching fastly cli

**Additional context**
See https://github.com/NixOS/nixpkgs/issues/219897

**Comment by Integralist** [comment]
Hi @shyim 👋🏻 

Thanks for opening this issue. We have an internal ticket tracking this work and although I can't give an exact time for when this will be done, it has been scheduled into our current sprint so I hope to start work on this soon.

**Comment by Integralist** [comment]
👋🏻 @shyim so following on from my earlier comments...

You'll need [Viceroy](https://github.com/fastly/viceroy) installed for `compute serve` to run successfully. 

That means you'll ultimately need to have your CI pipeline install Viceroy and then the following PR should address the CLI side of the issue: https://github.com/fastly/cli/pull/859

**Comment by shyim** [comment]
The PR looks very good and we can use it as it is for nixpkgs?

**Comment by Integralist** [comment]
👋🏻 @shyim So I don't know if this will necessarily be a _seamless_ solution to your issue.

My understanding (from your issue description) is that NixOS requires you to package a binary (e.g. the Fastly CLI) with any external dependencies (e.g. Viceroy) and so I imagine your CI pipeline for creating a Fastly CLI package for NixOS would do something like... 

1. Install Viceroy manually
2. Install the Fastly CLI (a version based off my PR when it's eventually merged/released)
3. Package up both binaries for NixOS

Now I don't know how NixOS unwraps packages but I presume it copies the dependent binaries (e.g. viceroy) into the user's path.

So with [my PR](https://github.com/fastly/cli/pull/859) it would then be up to the user to set `export FASTLY_VICEROY_USE_PATH=1` unless (as part of the NixOS packaging process) you're able to configure environment variables that are set when installing a NixOS package (I doubt that's possible but I mention it just in case, because if so, your NixOS package could auto-set the `FASTLY_VICEROY_USE_PATH` in that case).

**Comment by Integralist** [comment]
Closed by https://github.com/fastly/cli/pull/859

**Comment by ereslibre** [comment]
Thank you @Integralist! Lightning fast!

**Comment by Integralist** [comment]
Hopefully I'll have a new CLI release out before the end of the week.
