### ISSUE TITLE
Working with an expired token yields non-obvious errors.

### ISSUE THREAD

**Issue by deweerdt** [fastly/cli#894]
**Version**

v8.2.1

**What happened**

I tried to run the cli with an expired token, and got errors such as:
```
error creating service: 404 - Not Found:

    Title:  Record not found
    Detail: Cannot find 'service'
```

It would be nice if the error message accompanying 404s suggested to look into the token or auth problems.

**Comment by Integralist** [comment]
Hi @deweerdt 

Thanks for raising this issue. The ambiguous error message is actually stemming from the Fastly API rather than the CLI, and so I've raised it internally with the appropriate team and they have created a bug ticket to track a fix. 

Unfortunately, I can't give you an estimate as to when it will be resolved but I just wanted to let you know that although I'm going to close this CLI issue, we are now aware of the API issue and are actively tracking it.
