### ISSUE TITLE
New CLI version blocks deployment due to package size

### ISSUE THREAD

**Issue by platy** [fastly/cli#978]
**Version**

Fastly CLI version v10.2.3 (6cdda9c1)
Built with go version go1.20.6 linux/amd64
Viceroy version: viceroy 0.6.0

**What happened**

I ran

```
fastly compute deploy
```

and it deployed like normal, then I ran 

```
fastly update
```

and updated the CLI to the version released today, then ran deploy again and got the error:

```
ERROR: package size exceeded 100MB limit.
```

I was expecting it to deploy my app again. There hasn't been a large change in package size for a while, compressed it is well under 100MB, but uncompressed it is well over, I assumed that the limit applied to the compressed archive as otherwise we would be over the limit.

Is this an error, introduced in the new version, or is this correcting an error to enforce a limit which wasn't previously enforced? Though I assume some limit is enforced on the backend, but that must be a different limit to this.

**Comment by Integralist** [comment]
👋🏻 Hi @platy 

Were you using `v10.2.2` prior to this and the error wasn't present in that version?

There was a change made in the CLI related to package size but if anything this change was to _increase_ the size 🙂 

https://github.com/fastly/cli/commit/2d4de81d4651b220134b383d91aadbea2580cf13

In the above change set (released in version [`v10.1.0`](https://github.com/fastly/cli/releases/tag/v10.1.0)) the size of the package was 50mb and we up'ed it to 100mb (because that was the _actual_ limitation on the API side).

Thanks.

**Comment by platy** [comment]
Hi @Integralist 

I don't have this issue with v10.2.2, I've confirmed that by grabbing the binary release for it and no problems. The error I'm hitting is a check on the sum of the files inside the archive, not on the overall package size. It isn't new in the latest version, but the code for it did move, so maybe it moved from a path I wasn't hitting to one that I now am.

What is this code for, it definitely looks like it is intentionally limiting the size of the contents of the package?:

https://github.com/fastly/cli/commit/b45171642a087328bfa5c8e063197ddb1ac8c70d#diff-323540d61ef576278983a97fd16cf6af59fbacded7d0b250bc97cd54718df94aR108-R121

**Comment by Integralist** [comment]
Closing for now as we have removed the faulty logic in the CLI (see PR https://github.com/fastly/cli/pull/984)

https://github.com/fastly/cli/releases/tag/v10.2.4
